version: "3.9"

services:
  app:
    build: .
    image: natours-app
    container_name: natours-app
    ports:
      - "3000:3000" 
    env_file:
      - ./config.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: natours-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: natours-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:

